version: '3.8'

services:
  db:
    image: postgres:15
    container_name: testresults-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testresults
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./src
    container_name: testresults-api
    depends_on:
      - db
    ports:
      - "4567:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=testresults;Username=postgres;Password=password"

volumes:
  pgdata:
